#!/usr/bin/env bash

###############################
# SYSMIG Migration Script     #
# Autogenerated (DO NOT EDIT) #
###############################

# Exit on error is enabled
set -e

#############
# Migration #
#############

echo Migrating your system to the latest state
%s

##############
# State Sync #
##############

echo Updating state for future migrations

state_base64="%s"
state_path="%s"
echo -n $state_base64 | base64 -d > $state_path

################
# All done! :) #
################

echo Finished
