#!/usr/bin/env bash

###############################
# SYSMIG Sync Script          #
# Autogenerated (DO NOT EDIT) #
###############################

# Exit on error is enabled
set -e

###########
# Syncing #
###########

echo Syncing your system state
%s

#########################
# Update last sync time #
#########################

last_sync_path="%s"
date +%s > $last_sync_path

################
# All done! :) #
################

echo Finished
