#!/usr/bin/env bash

###############################
# SYSMIG Sync Script          #
# Autogenerated (DO NOT EDIT) #
###############################

# Exit on error is enabled
set -e

###########
# Syncing #
###########

echo Syncing your system state
%s

################
# All done! :) #
################

echo Finished