name: Release
on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-*
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - run: make
      - uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE.md
          files: sysmig
