name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - run: go build
      - uses: softprops/action-gh-release@v2
        with:
          body_path: manifest/release.md
          files: sysmig